Allow upgrades when initializing Terraform
Other developers may have updated packages since you last init'ed. In
this case -upgrade seems to be required. Otherwise Terraform will
complain.

Example:

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/azurerm: locked provider registry.terraform.io/hashicorp/azurerm 3.30.0 does not match configured version constraint >= 3.33.0; must use terraform init -upgrade to allow selection of new versions